//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlackWindowsTray {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class SlackWindowsTray : global::System.Configuration.ApplicationSettingsBase {
        
        private static SlackWindowsTray defaultInstance = ((SlackWindowsTray)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SlackWindowsTray())));
        
        public static SlackWindowsTray Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int SnoozeAllTimeMinutes {
            get {
                return ((int)(this["SnoozeAllTimeMinutes"]));
            }
            set {
                this["SnoozeAllTimeMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int SnoozeChatTimeMinutes {
            get {
                return ((int)(this["SnoozeChatTimeMinutes"]));
            }
            set {
                this["SnoozeChatTimeMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToBlinkOnUnread {
            get {
                return ((bool)(this["ToBlinkOnUnread"]));
            }
            set {
                this["ToBlinkOnUnread"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToBlinkOnMention {
            get {
                return ((bool)(this["ToBlinkOnMention"]));
            }
            set {
                this["ToBlinkOnMention"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SlackToken {
            get {
                return ((string)(this["SlackToken"]));
            }
            set {
                this["SlackToken"] = value;
            }
        }
    }
}
